UI-Änderungen für Abfahrtstafel & Verbindungen
derf/travelynx pull request #93
Opened 2023-10-22 14:53 UTC by deingithub

Nochmal ein bisschen angepasst von #92:

Größere Font für Stationsnamen, Wechsel zwischen HAFAS und IRIS erfolgt jetzt über einen Button, direkt daneben ist ein zweiter Button um zum Anfragezeitpunkt zu springen. Die Verbindungen und Abfahrten sind jetzt color-coded nach Zuggattung, ein paar Erste hab ich hinzugefügt. Nahverkehrsmittel und Schnellbahnen sind abgerundet, der Rest etwas eckiger. Selects für Datenquelle und Filter entfallen, die kleinen Buttons oben brauchen etwa halb so viel vertikalen Platz.
![image](https://github.com/derf/travelynx/assets/46252311/64ef538c-d404-4ef6-934b-8df4b81151cd)

Ausfallende Züge werden farblich hervorgehoben und nochmal als Text beschrieben:
![Screenshot from 2023-10-22 16-33-40](https://github.com/derf/travelynx/assets/46252311/7e24c6f9-f5a7-462e-afa4-f64f6b047501)

Die Anzeige, dass ein Followee in einem Zug eingecheckt ist, habe ich auch mit dem Follower-Icon versehen und den entsprechenden Code auch in die HAFAS-Template reinkopiert, da war er noch nicht¹:
![Screenshot from 2023-10-22 16-22-12](https://github.com/derf/travelynx/assets/46252311/75765f31-8e87-4a05-a6fc-df2335d73af9)

Wenn der Viewport schmaler als die Materialize-Grenze small wird (600px), wird das Layout schmaler und dafür höher:
![Screen Shot 2023-10-22 at 16 45 53](https://github.com/derf/travelynx/assets/46252311/4f70bd9a-d166-43ab-98fb-3ec5dd7704a6)
![Screen Shot 2023-10-22 at 16 49 12](https://github.com/derf/travelynx/assets/46252311/5fb55261-0010-41ce-80ad-9dd249c2ff08)

Die Zeilen der Collection haben einen Hover-Effekt, der die aktuelle Zeile im selben Grauton wie die Anfragezeitpunkt-Zeile hervorhebt. In jeder Zeile habe einheitlich nur die Uhrzeit zum `<a>` Tag gemacht und ihr jeweils auch einen `href="#"` gegeben, sodass man mit Tab durch die Abfahrten navigieren kann.

Was auf jeden Fall noch fehlt, ist das Asset Release, den Vorgang verstehe ich nicht.

--- 
¹ Das scheint auf ersten Blick zu funktionieren, allerdings findet die IRIS-Seite aber nur IRIS-Checkins und die HAFAS-Seite nur HAFAS-Checkins von Followees. Das ist denke ich nicht so schlimm, da einen Travelynx ja alle einheitlich auf die bevorzugte Seite für jede Station leitet.

2023-10-25 13:46 UTC, derf commented
Sieht soweit sehr schön aus, vielen Dank!

Bevor ich das in Ruhe anschauen und mergen kann werden noch ein paar Tage vergehen.
Einen kleinen Nitpick hätte ich schonmal: Die rote Hintergrundfarbe für ausgefallene Fahrten finde ich im dark mode etwas zu auffällig, gerade verglichen mit dem light mode.
Magst du die noch etwas dezenter (also näher an der Hintergrundfarbe, ähnlich zu Ausfällen im light mode) machen?

2023-10-26 05:00 UTC, derf commented
Oh, und bevor ich es vergesse: Wie magst du im Changelog erwähnt werden, einfach "@deingithub" und fertig?

2023-10-26 09:55 UTC, deingithub commented
Passt das so eher?
![Screenshot from 2023-10-26 11-53-17](https://github.com/derf/travelynx/assets/46252311/b15e68d7-c96b-4dab-88fa-4ed15c413816)
![Screenshot from 2023-10-26 11-53-11](https://github.com/derf/travelynx/assets/46252311/9d811702-9a51-4ae5-abb2-83a140249d1c)

2023-10-26 17:07 UTC, derf commented
Schaut gut aus :) wenn nix dazwischenkommt geht's in ein paar Tagen so live

2023-10-27 16:33 UTC, derf requested changes

2023-10-27 16:33 UTC, derf commented on templates/_connections.html.ep
> +				<span class="dep-line <%= (split(/ /, $train->line))[0] %>">
Note: there are trains that do not have a line type, e.g. in Belgium. In that case, this piece of code will return the train number instead, which is not helpful but also not harmful.

I'll quickly replace it with `$train->type` here and in the other three cases.

2023-10-27 16:33 UTC, derf commented on templates/_connections_hafas.html.ep
> +				<span class="dep-line <%= (split(/ /, $train->line))[0] %>">
(same here)

2023-10-27 16:33 UTC, derf commented on templates/_departures_hafas.html.ep
> +		<span class="dep-line <%= (split(/ /, $result->line))[0] %>">
(same here)

2023-10-27 16:33 UTC, derf commented on templates/_departures_iris.html.ep
> +			<span class="dep-line <%= (split(/ /, $result->line))[0] %>">
(same here)

2023-10-27 16:36 UTC, derf approved these changes
… okay, I think I'm holding this GitHub PR review thingy slightly wrong, but anyways, that should be it

2023-10-27 16:40 UTC, merged